name: markdown_live_editor
description: A controller to create reactive markdown editors.
version: 0.1.0-alpha
repository: https://github.com/bleaklake/flutter_markdown_live_editor

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  dart_markdown: ^3.1.7
  source_span: ^1.10.0
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
